- name: Install grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_5.4.2_amd64.deb

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Upload the example Grafana dashboard."
  uri:
    url: http://127.0.0.1:3000/api/dashboards/db
    method: POST
    body: "{{ lookup('file', 'infra-node-metrics.json') }}"
    body_format: json
    user: admin
    password: admin
    force_basic_auth: yes
    status_code: 200
    headers:
      Content-Type: "application/json"
      Accept: "application/json"

- name: "Check if Grafana is accessible."
  uri:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200
    

- name: "Add Prometheus as datasource to Grafana."       
  vars:
    prometheus_datasource:
        name: "prometheus"
        type: "prometheus"
        url: "http://127.0.0.1:9090"
        access: "proxy"
        isDefault: true
        basicAuth: false
  uri:
    url: http://127.0.0.1:3000/api/datasources
    method: POST
    body: "{{ prometheus_datasource | to_json }}"
    body_format: json
    user: admin
    password: admin
    force_basic_auth: yes
    status_code: 200,500  # 500 means, the datasource is already added
    headers:
        Content-Type: "application/json"
        Accept: "application/json"   